# Generated by Django 3.2.6 on 2021-09-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='monto_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
