# Generated by Django 3.2.6 on 2021-09-08 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversion',
            old_name='id_moneda1',
            new_name='id_medida1',
        ),
        migrations.RenameField(
            model_name='conversion',
            old_name='id_moneda2',
            new_name='id_medida2',
        ),
        migrations.AlterUniqueTogether(
            name='conversion',
            unique_together={('id_medida1', 'id_medida2')},
        ),
        migrations.CreateModel(
            name='Conversion_Moneda',
            fields=[
                ('id_moneda1', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_moneda2', models.CharField(max_length=6)),
                ('factor', models.IntegerField(blank=True, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('id_moneda1', 'id_moneda2')},
            },
        ),
    ]
