# Generated by Django 3.2.6 on 2021-09-08 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionProductos', '0003_auto_20210908_1105'),
        ('GestionPersonas', '0007_auto_20210908_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Ticket',
            fields=[
                ('id_est_ticket', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=12, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=12, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('monto_total', models.IntegerField(blank=True, null=True)),
                ('fecha_compra', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('user_creacion', models.CharField(blank=True, default='USR-0000001', max_length=12, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=12, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('id_est_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionPedidos.estado_ticket')),
                ('id_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Ticket',
            fields=[
                ('id_tipo_ticket', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=12, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=12, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Producto',
            fields=[
                ('id_prod_ticket', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('secuencia', models.IntegerField()),
                ('p_unitario', models.IntegerField()),
                ('cantidad', models.IntegerField(default=1)),
                ('comentario', models.CharField(blank=True, max_length=1500, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.producto')),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPedidos.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_tipo_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionPedidos.tipo_ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='recepcionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.usuario'),
        ),
    ]
