# Generated by Django 3.2.6 on 2021-09-07 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id_party', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo_party', models.CharField(max_length=200)),
                ('user_creacion', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField()),
                ('user_actualizacion', models.CharField(max_length=10)),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GestionPersonas.party')),
                ('ruc', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=1500)),
                ('giro_comercial', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GestionPersonas.party')),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=1500)),
                ('apellidos', models.CharField(max_length=1500)),
                ('sexo', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
