# Generated by Django 3.2.6 on 2021-09-07 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonas', '0003_estado_mecanismo_estado_usuario_mecanismo_contacto_tipo_mecanismo_tipo_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_usuario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2021, 9, 7, 14, 5, 26, 676742)),
        ),
        migrations.AlterField(
            model_name='party',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='tipo_party',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2021, 9, 7, 14, 5, 26, 676742)),
        ),
    ]
