# Generated by Django 3.2.6 on 2021-09-07 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonas', '0004_auto_20210907_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 7, 14, 16, 48, 924471), null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pass_word',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estado_mecanismo',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estado_mecanismo',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 7, 14, 16, 48, 922445), null=True),
        ),
        migrations.AlterField(
            model_name='estado_mecanismo',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estado_mecanismo',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estado_rol',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estado_rol',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 7, 14, 16, 48, 922445), null=True),
        ),
        migrations.AlterField(
            model_name='estado_rol',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estado_rol',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estado_usuario',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estado_usuario',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 7, 14, 16, 48, 924471), null=True),
        ),
        migrations.AlterField(
            model_name='estado_usuario',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estado_usuario',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mecanismo_contacto',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mecanismo_contacto',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 7, 14, 16, 48, 923476), null=True),
        ),
        migrations.AlterField(
            model_name='mecanismo_contacto',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mecanismo_contacto',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 7, 14, 16, 48, 921449), null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 7, 14, 16, 48, 921449), null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rol_party',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rol_party',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 7, 14, 16, 48, 922445), null=True),
        ),
        migrations.AlterField(
            model_name='rol_party',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rol_party',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_mecanismo',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_mecanismo',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 7, 14, 16, 48, 923476), null=True),
        ),
        migrations.AlterField(
            model_name='tipo_mecanismo',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_mecanismo',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 7, 14, 16, 48, 923476), null=True),
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
