# Generated by Django 3.2.6 on 2021-09-07 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonas', '0005_auto_20210907_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_mecanismo',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='estado_rol',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='estado_usuario',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='mecanismo_contacto',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='rol_party',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_mecanismo',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
