# Generated by Django 3.2.6 on 2021-09-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonas', '0006_auto_20210907_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_mecanismo',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='estado_mecanismo',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='estado_rol',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='estado_rol',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='estado_usuario',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='estado_usuario',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='mecanismo_contacto',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='mecanismo_contacto',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='rol_party',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='rol_party',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_mecanismo',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_mecanismo',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_actualizacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_creacion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
