# Generated by Django 3.2.6 on 2021-09-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Rol',
            fields=[
                ('id_est_rol', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1500)),
                ('user_creacion', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField()),
                ('user_actualizacion', models.CharField(max_length=10)),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('tipo_rol', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=1500)),
                ('user_creacion', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField()),
                ('user_actualizacion', models.CharField(max_length=10)),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='party',
            name='id_party',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Rol_Party',
            fields=[
                ('id_Rol_Pary', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('user_creacion', models.CharField(max_length=10)),
                ('user_actualizacion', models.CharField(max_length=10)),
                ('id_est_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.estado_rol')),
                ('id_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.party')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.rol')),
            ],
        ),
    ]
