# Generated by Django 3.2.6 on 2021-09-07 18:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonas', '0002_auto_20210907_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Mecanismo',
            fields=[
                ('id_estado_mec', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1500)),
                ('user_creacion', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField()),
                ('user_actualizacion', models.CharField(max_length=10)),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Usuario',
            fields=[
                ('id_est_user', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1500)),
                ('user_creacion', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField(default=datetime.datetime(2021, 9, 7, 13, 57, 16, 4307))),
                ('user_actualizacion', models.CharField(max_length=10)),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Mecanismo',
            fields=[
                ('id_tipo_mec', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1500)),
                ('user_creacion', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField()),
                ('user_actualizacion', models.CharField(max_length=10)),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id_tipo_user', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1500)),
                ('user_creacion', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField(default=datetime.datetime(2021, 9, 7, 13, 57, 16, 3310))),
                ('user_actualizacion', models.CharField(max_length=10)),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('id_est_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.estado_usuario')),
                ('id_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.party')),
                ('id_tipo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanismo_Contacto',
            fields=[
                ('id_mec_cont', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1500)),
                ('user_creacion', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField()),
                ('user_actualizacion', models.CharField(max_length=10)),
                ('fecha_actualizacion', models.DateField()),
                ('id_estado_mec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.estado_rol')),
                ('id_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.party')),
                ('id_tipo_mec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.tipo_mecanismo')),
            ],
        ),
    ]
