# Generated by Django 3.2.6 on 2021-09-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonas', '0007_auto_20210908_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol_party',
            old_name='id_Rol_Pary',
            new_name='id_rol_party',
        ),
    ]
