# Generated by Django 3.2.6 on 2021-09-08 03:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionPersonas', '0006_auto_20210907_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id_caracteristica', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Caracteristica',
            fields=[
                ('id_est_carac', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Precio',
            fields=[
                ('id_est_pre', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Producto',
            fields=[
                ('id_est_prod', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id_moneda', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sobre_Costo',
            fields=[
                ('id_sobrecosto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('rangomin', models.IntegerField(blank=True, null=True)),
                ('rangomx', models.IntegerField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id_tienda', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=1500, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('referencia', models.CharField(blank=True, max_length=1500, null=True)),
                ('direccion', models.CharField(blank=True, max_length=1500, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('id_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.party')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Caracteristica',
            fields=[
                ('id_tipo_carac', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Precio',
            fields=[
                ('id_tipo_pre', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('id_tipo_prod', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda_Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('id_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.tienda')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.categoria')),
                ('id_est_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.estado_producto')),
                ('id_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.medida')),
                ('id_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.tienda')),
                ('id_tipo_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.tipo_producto')),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id_moneda1', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_moneda2', models.CharField(max_length=6)),
                ('factor', models.IntegerField(blank=True, null=True)),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('id_moneda1', 'id_moneda2')},
            },
        ),
        migrations.CreateModel(
            name='Componente_Costo',
            fields=[
                ('id_precio', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=1500, null=True)),
                ('valor', models.IntegerField()),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('id_caracteristica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.caracteristica')),
                ('id_est_pre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.estado_precio')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.moneda')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.producto')),
                ('id_sobrecosto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.sobre_costo')),
                ('id_tipo_pre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.tipo_precio')),
            ],
        ),
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_creacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_actualizacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='id_est_carac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.estado_caracteristica'),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='id_tipo_carac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.tipo_caracteristica'),
        ),
    ]
